config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top' 
  get '/about' => 'homes#about'
  resources :articles, only: [:index,:show]
  resources :chiropractors, only: [:index] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create]
  end
  
  devise_for :chiropractors, controllers: {
  sessions: 'chiropractors/sessions',
  passwords: 'chiropractors/passwords',
  registrations: 'chiropractors/registrations'
  }
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations'
  
  }
  
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }
  
  namespace :admin do
    resources :articles, only: [:new, :create, :edit, :update, :delete]
  end
  
  namespace :chiropractor do
    resources :chiropractors, only: [:show, :edit, :update]
  end
  
  namespace :user do
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :articles, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  #画像投稿用(refile)
  attachment :image
  
  belongs_to :admin
end

app/models/chiropractor.rb
class Chiropractor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  #画像投稿用(refile)
  attachment :image
  
  enum sex: {
    male: 1,
    female: 2,
    not_applicable: 0,
  }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :chiropractor
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :chiropractor
  
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
   #画像投稿用(refile)
  attachment :image
  
  def favorited_by?(chiropractor_id)
    favorites.where(chiropractor_id: chiropractor_id).exists?
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.admin_id = 1
    @article.genre_id = 1
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article.id)
    else
     @article = Article.find(params[:id])
      render :edit
    end
  end
  
  def destroy
  end
  
  private
  def article_params
     params.require(:article).permit(:title, :image, :body, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def after_sign_in_path_for(resource)
    case resource
    when User
      user_user_path(resource)
    when Chiropractor
      chiropractor_chiropractor_path(resource)
    when Admin
      root_path
    end
  end
  
  def after_sign_up_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    if resource == :user
      root_path
    elsif resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [
        :nickname,
        :name,
        :postal_code,
        :prefecture_code,
        :address_city,
        :address_strret,
        :fare,
        :service_charge,
        :age,
        :sex,
        :nearest_station,
        :treatment_time,
        :phone_number,
        :email
        ]
    )
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/chiropractors_controller.rb
class ChiropractorsController < ApplicationController
  def index
    @chiropractors = Chiropractor.all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    Favorite.create(user_id: current_user.id, chiropractor_id: params[:chiropractor_id])
    redirect_to chiropractor_chiropractor_path(params[:chiropractor_id])
  end
  
  def destroy
    Favorite.find_by(user_id: current_user.id, chiropractor_id: params[:chiropractor_id]).destroy
    redirect_to chiropractor_chiropractor_path(params[:chiropractor_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_user_path(@user.id)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit( :nickname, :name, :postal_code,:prefecture_code, :address_city, :address_street,
    :phone_number, :email, :image)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chiropractors_helper.rb
module ChiropractorsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/articles/edit.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>ARTICELS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>EDIT<span>
    
<div class="PageHead-article">
  <div class="PageHead-article_title">
    <h2>ARTICLES</h2>
  </div>
  <div class="PageHead-article_text">
    <h2>投稿された記事の編集ページです。</h2>
  </div>
</div>

<div class="article-edit_display">
  <%= form_with model:@article, url: admin_article_path, local:true do |f| %>
    <div class="article-display_form">
      <h4>タイトル</h4>
      <div class="form-group form-inline">
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"form-control col-sm-7"  %>
      </div>
    
      <h4>サムネイル用画像</h4>
      <div class="form-group form-inline">
        <%= f.attachment_field :image,class:"col-sm-7" %>
      </div>
    
      <h4>本文</h4>
      <div class="form-group form-inline">
        <%= f.text_area :body, autofocus: true, autocomplete: "body", size: "30x40", class:"form-control col-sm-7" %>
      </div>

      <div class="article-button">
        <%= f.submit "編集した記事を投稿する", class:"btn btn-secondary col-sm-6" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/articles/new.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>ARTICELS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>POST<span>
    
<div class="PageHead-article">
  <div class="PageHead-article_title">
    <h2>ARTICLES</h2>
  </div>
  <div class="PageHead-article_text">
    <h2>ABOUT</h2>
  </div>
  
<div class="article-display">
  <h1 class="article-display_title">New Post</h1>
  <%= form_with model:@article, url: admin_articles_path, local:true do |f| %>
    <div class="article-display_form">
      <h4>タイトル</h4>
      <div class="form-group form-inline">
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"form-control col-sm-7"  %>
      </div>
    
      <h4>サムネイル用画像</h4>
      <div class="form-group form-inline">
        <%= f.attachment_field :image,class:"col-sm-7" %>
      </div>
    
      <h4>本文</h4>
      <div class="form-group form-inline">
        <%= f.text_area :body, autofocus: true, autocomplete: "body", size: "30x40", class:"form-control col-sm-7" %>
      </div>

      <div class="article-button">
        <%= f.submit "記事を投稿する", class:"btn btn-secondary col-sm-6" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>ARTICELS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>INDEX<span>
    
<div class="PageHead-article">
  <div class="PageHead-article_title">
    <h2>ARTICLES</h2>
  </div>
  <div class="PageHead-article_text">
    <h2>投稿された記事の一覧ページです。</h2>
  </div>
  
<div class="article-display">
  <% @articles.each do |article| %>
    <div class="article-box">
      <%= link_to(article_path(article)) do %>
        <h6 class="article-box_date"><%= article.created_at.strftime('%Y/%m/%d') %></h6>
        <h4 class="article-box_title"><%= article.title %><h4>
        <%= attachment_image_tag(article, :image, format: 'jpeg',class: "article-box_image") %>
        <h6 class="article-box_text"><%= article.body.truncate(20) %></h6>
      <% end %>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>ARTICELS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>SHOW<span>
    
<div class="PageHead-article">
  <div class="PageHead-article_title">
    <h2>ARTICLES</h2>
  </div>
  <div class="PageHead-article_text">
    <h2>投稿された記事の詳細ページです。</h2>
  </div>
  
<div class="article_show-display">
  <%= attachment_image_tag( @article, :image, width:"110px", format: 'jpeg',class: "article-show_image") %>
  <h6 class="article-show_date"><%= @article.created_at.strftime('%Y/%m/%d') %></h6>
  <h2 class="article-show_title"><%= @article.title %><h2>
  <h6 class="article-show_text"><%= markdown(@article.body).html_safe %></h6>
  <%= link_to"編集する", edit_admin_article_path(@article), class:"btn btn-secondary article_button" %>
</div>