config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top' 
  get '/about' => 'homes#about'
  resources :articles, only: [:index,:show]
  resources :chiropractors, only: [:index] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create]
  end
  
  devise_for :chiropractors, controllers: {
  sessions: 'chiropractors/sessions',
  passwords: 'chiropractors/passwords',
  registrations: 'chiropractors/registrations'
  }
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations'
  
  }
  
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }
  
  namespace :admin do
    resources :articles, only: [:new, :create, :edit, :update, :delete]
  end
  
  namespace :chiropractor do
    resources :chiropractors, only: [:show, :edit, :update]
  end
  
  namespace :user do
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/chiropractor.rb
class Chiropractor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  #画像投稿用(refile)
  attachment :image
  
  enum sex: {
    male: 1,
    female: 2,
    not_applicable: 0,
  }
end

app/controllers/chiropractor/chiropractors_controller.rb
class Chiropractor::ChiropractorsController < ApplicationController
  def show
    @chiropractor = Chiropractor.find(params[:id])
  end
  
  def edit
    @chiropractor = Chiropractor.find(params[:id ])
  end
  
  def update
    @chiropractor = Chiropractor.find(params[:id ])
    if @chiropractor.update(chiropractor_params)
      redirect_to chiropractor_chiropractor_path(@chiropractor.id)
    else
      @chiropractor = Chiropractor.find(params[:id ])
      render :edit
    end
  end
  
  private
  def chiropractor_params
    params.require(:chiropractor).permit(:treatment_id, :nickname, :name, :postal_code,:prefecture_code, :address_city, :address_street,
    :phone_number, :email, :image, :fare, :service_charge, :age, :nearest_station, :sex, :treatment_time)
  end
end

app/controllers/chiropractors/confirmations_controller.rb
# frozen_string_literal: true

class Chiropractors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/chiropractors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Chiropractors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/chiropractors/passwords_controller.rb
# frozen_string_literal: true

class Chiropractors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/chiropractors/registrations_controller.rb
# frozen_string_literal: true

class Chiropractors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/chiropractors/sessions_controller.rb
# frozen_string_literal: true

class Chiropractors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/chiropractors/unlocks_controller.rb
# frozen_string_literal: true

class Chiropractors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/chiropractors_controller.rb
class ChiropractorsController < ApplicationController
  def index
    @chiropractors = Chiropractor.all
  end
end

app/helpers/chiropractor/chiropractors_helper.rb
module Chiropractor::ChiropractorsHelper
end

app/helpers/chiropractors_helper.rb
module ChiropractorsHelper
end

app/views/chiropractor/chiropractors/edit.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>CHIROPRACTORS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>EDIT<span>
    
<div class="PageHead_practator">
  <div class="PageHead_practator-title">
    <h2>CHIROPRACTORS</h2>
  </div>
  <div class="PageHead_practator-text">
    <h2><%=@chiropractor.nickname%>の編集ページ</h2>
  </div>
</div>

<div class="chiropractor_edit-display">
  <h1 class="chiropractor_edit-display_title">EDIT</h1>
  <h4 class="chiropractor_edit-display_text">
    必要情報の更新を行います。<br><br>
    以下の項目を入力していただき、「編集完了」ボタンを押してください。
  </h4>
  <p class="signup-display_text2"><span class="required_item">*</span>は必須項目です。</p>
  <%= form_with model:@chiropractor, url: chiropractor_chiropractor_path(@chiropractor), local:true do |f| %>
    <div class="chiropractor_edit-display_form">
      <div class="form-group form-inline">
        <%= f.label :nickname, 'ニックネーム', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", placeholder: "", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :name, 'お名前（姓・名）', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "氏名（姓・名）", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline">
        <%= f.label :sex, "性別", class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.radio_button :sex, "male", checked: true %>
        <h5 class="mt-2 ml-1">男性</h5>
        <%= f.radio_button :sex, "female", class:"ml-4" %>
        <h5 class="mt-2 ml-1">女性</h5>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :image, 'プロフィール画像', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.attachment_field :image, class:"col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :postal_code, '郵便番号', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "0000000", class:"form-control col-sm-2" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <div class="col-sm-2"></div>
        <%= f.text_field :address_city, autofocus: true, autocomplete: "address_city", placeholder: "市区町村名", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <div class="col-sm-2"></div>
        <%= f.text_field :address_street, autofocus: true, autocomplete: ":address_street", placeholder: "番地・ビル名", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :nearest_station, '最寄り駅', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :nearest_station, autofocus: true, autocomplete: "nearest_station", placeholder: "東京駅", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :service_charge, 'サービス料', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :service_charge, autofocus: true, autocomplete: "service_charge", placeholder: "一時間当たりのサービス料を入力してください。", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :fare, '運賃料', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :fare, autofocus: true, autocomplete: "service_charge", placeholder: "運賃料を入力してください。", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :age, '年齢', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :age, autofocus: true, autocomplete: "age", placeholder: "数字のみを入力してください。", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :phone_number, '電話番号', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "00000000000", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :email, 'メールアドレス', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "sample@example.com", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :treatment_time, '施術時間', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :treatment_time, autofocus: true, autocomplete: "treatment_time", placeholder: "施術時間を数字のみ入力してください。", class:"form-control col-sm-4" %>
      </div>

      <div class="signup-button">
        <%= f.submit "編集完了", class:"btn btn-secondary col-sm-6" %>
      </div>
    </div>
  <% end %>
</div>

app/views/chiropractor/chiropractors/show.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>CHIROPRACTORS<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>SHOW<span>
    
<div class="PageHead_practator">
  <div class="PageHead_practator-title">
    <h2>CHIROPRACTORS</h2>
  </div>
  <div class="PageHead_practator-text">
    <h2><%=@chiropractor.nickname%>の詳細ページ</h2>
  </div>
</div>
  
<div class="chiropractor_show-display">
  <div class="chiropractor_profile">
    <h2 class="chiropractor_profile-name"><%= @chiropractor.nickname %></h2>
    <%#ここからいいね機能%>
    <% if current_user.favorited_by?(@chiropractor.id) %>
      <%= link_to chiropractor_favorites_path(@chiropractor), method: :delete, local: true do %>
        <p class="text-danger favorites">
          <i class="fa fa-lg fa-heart" aria-hidden="true"></i>
        </p>
      <% end %>
    <% else %>
      <%= link_to chiropractor_favorites_path(@chiropractor), method: :post, local: true do %>
        <p class="text-secondary favorites">
          <i class="fa fa-lg fa-heart" aria-hidden="true"></i>
        </p>
      <% end %>
    <% end %>
    <%#ここまでいいね機能%>
    <%= attachment_image_tag(@chiropractor, :image, width:"90px", format: 'jpeg', fallback: "no-image.png",class: "chiropractor_image") %>
    <%= link_to "EDIT", edit_chiropractor_chiropractor_path(@chiropractor), class: "btn btn-secondary col-sm-6 btn_edit" %>
    <h2 class="performance">📄Performance</h2>
    <h2 class="price">💰Price</h2>
    <h4 class="fee">🚃Fare　　　 &nbsp;¥<%=@chiropractor.fare.to_s(:delimited) %></h4><br>
    <h4 class="fee">Service Charge¥<%=@chiropractor.service_charge.to_s(:delimited) %></h4>
    <h2 class="profile">👤Profile</h2>
    <h4 class="profile_text">Age　　<%= @chiropractor.age %>歳</h4><br>
    <h4 class="profile_text">Sex　　
      <% if @chiropractor.sex == "male" %>
        male
      <% elsif @chiropractor.sex == "female" %>
        female
      <% end %>
    </h4>
    <h2 class="method">Method</h2>
  </div>
</div>