config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top' 
  get '/about' => 'homes#about'
  resources :articles, only: [:index,:show]
  resources :chiropractors, only: [:index] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create]
  end
  
  devise_for :chiropractors, controllers: {
  sessions: 'chiropractors/sessions',
  passwords: 'chiropractors/passwords',
  registrations: 'chiropractors/registrations'
  }
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations'
  
  }
  
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }
  
  namespace :admin do
    resources :articles, only: [:new, :create, :edit, :update, :delete]
  end
  
  namespace :chiropractor do
    resources :chiropractors, only: [:show, :edit, :update]
  end
  
  namespace :user do
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
   #画像投稿用(refile)
  attachment :image
  
  def favorited_by?(chiropractor_id)
    favorites.where(chiropractor_id: chiropractor_id).exists?
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
    
  def create
    Favorite.create(user_id: current_user.id, chiropractor_id: params[:id])
    redirect_to chiropractors_path
  end
  
  def destroy
    Favorite.find_by(user_id: current_user.id, chiropractor_id: params[:id]).destroy
    redirect_to chiropractors_path
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_user_path(@user.id)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit( :nickname, :name, :postal_code,:prefecture_code, :address_city, :address_street,
    :phone_number, :email, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>USER<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>EDIT<span>
    
<div class="PageHead_practator">
  <div class="PageHead_practator-title">
    <h2>USER</h2>
  </div>
  <div class="PageHead_practator-text">
    <h2>詳細ページ</h2>
  </div>
</div>

<div class="user_edit-display">
  <h1 class="user_edit-display_title">EDIT</h1>
  <h4 class="user_edit-display_text">
    必要情報の更新を行います。<br><br>
    以下の項目を入力していただき、「編集完了」ボタンを押してください。
  </h4>
  <%= form_with model:@user, url: user_user_path(@user), local:true do |f| %>
    <div class="user_edit-display_form">
      <div class="form-group form-inline">
        <%= f.label :nickname, 'ニックネーム', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", placeholder: "", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :name, 'お名前（姓・名）', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "氏名（姓・名）", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :image, 'プロフィール画像', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.attachment_field :image, class:"col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :postal_code, '郵便番号', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "0000000", class:"form-control col-sm-2" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <div class="col-sm-2"></div>
        <%= f.text_field :address_city, autofocus: true, autocomplete: "address_city", placeholder: "市区町村名", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <div class="col-sm-2"></div>
        <%= f.text_field :address_street, autofocus: true, autocomplete: ":address_street", placeholder: "番地・ビル名", class:"form-control col-sm-4" %>
      </div>
      
      <div class="form-group form-inline mt-4">
        <%= f.label :phone_number, '電話番号', class:"col-sm-2 control-label font-weight-lighter small" %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", placeholder: "00000000000", class:"form-control col-sm-4" %>
      </div>

      <div class="signup-button">
        <%= f.submit "編集完了", class:"btn btn-secondary col-sm-6" %>
      </div>
     </div>
    <% end %>
</div>

app/views/user/users/show.html.erb
<div class="breadcrumb-navigation">
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>USER<span>
  <i class="fa fa-angle-right">&nbsp;</i>
  <span>MYPAGE<span>
    
<div class="PageHead_user">
  <div class="PageHead_user-title">
    <h2>MYPAGE</h2>
  </div>
  <div class="PageHead_user-text">
    <h2><%= @user.name %>様のマイページです。</h2>
  </div>
</div>

<div class="mypage-display">
  <h1 class="mypage-display_title">MYPAGE</h1>
  <%= attachment_image_tag(@user, :image, width:"180px", format: 'jpeg', fallback: "no-image.png",class: "user_image") %>
  <h3 class="user_name"><%= @user.name %></h3>
  <%= link_to "プロフィールを編集する", edit_user_user_path(@user), class: "btn btn-secondary col-sm-2 btn_user_edit" %>
</div>