config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top' 
  get '/about' => 'homes#about'
  resources :articles, only: [:index,:show]
  resources :chiropractors, only: [:index] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create]
  end
  
  devise_for :chiropractors, controllers: {
  sessions: 'chiropractors/sessions',
  passwords: 'chiropractors/passwords',
  registrations: 'chiropractors/registrations'
  }
  
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  passwords: 'users/passwords',
  registrations: 'users/registrations'
  
  }
  
  devise_for :admins, controllers: {
  sessions: 'admins/sessions'
  }
  
  namespace :admin do
    resources :articles, only: [:new, :create, :edit, :update, :delete]
  end
  
  namespace :chiropractor do
    resources :chiropractors, only: [:show, :edit, :update]
  end
  
  namespace :user do
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :articles, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  #画像投稿用(refile)
  attachment :image
  
  belongs_to :admin
end

app/models/chiropractor.rb
class Chiropractor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  #画像投稿用(refile)
  attachment :image
  
  enum sex: {
    male: 1,
    female: 2,
    not_applicable: 0,
  }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :chiropractor
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :chiropractor
  
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
   #画像投稿用(refile)
  attachment :image
  
  def favorited_by?(chiropractor_id)
    favorites.where(chiropractor_id: chiropractor_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def after_sign_in_path_for(resource)
    case resource
    when User
      user_user_path(resource)
    when Chiropractor
      chiropractor_chiropractor_path(resource)
    when Admin
      root_path
    end
  end
  
  def after_sign_up_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource)
    if resource == :user
      root_path
    elsif resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [
        :nickname,
        :name,
        :postal_code,
        :prefecture_code,
        :address_city,
        :address_strret,
        :fare,
        :service_charge,
        :age,
        :sex,
        :nearest_station,
        :treatment_time,
        :phone_number,
        :email
        ]
    )
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/chiropractors_controller.rb
class ChiropractorsController < ApplicationController
  def index
    @chiropractors = Chiropractor.all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    Favorite.create(user_id: current_user.id, chiropractor_id: params[:chiropractor_id])
    redirect_to chiropractor_chiropractor_path(params[:chiropractor_id])
  end
  
  def destroy
    Favorite.find_by(user_id: current_user.id, chiropractor_id: params[:chiropractor_id]).destroy
    redirect_to chiropractor_chiropractor_path(params[:chiropractor_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chiropractors_helper.rb
module ChiropractorsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="l-header">
        <a href="/"><h1 class="header-logo"></h1></a>
        <nav>
          <ul class="nav-main">
            <li><%= link_to "HOME", root_path, class:"nav-color ml-5" %></li>
            <li><%= link_to "ABOUT", about_path, class:"nav-color ml-4" %></li>
            <li><%= link_to "ARTICLES", articles_path, class:"nav-color ml-4" %></li>
            <li><%= link_to "CHIROPRACTORS", chiropractors_path, class:"nav-color ml-4" %></li>
            <li><%= link_to "ADMINISTRATOR", new_admin_session_path, class:"nav-color ml-4" %></li>
            <% if user_signed_in? %>  
              <li><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class:"nav-color ml-4" %></li>
            <% end %>
            <% if chiropractor_signed_in? %>  
              <li><%= link_to "LOGOUT", destroy_chiropractor_session_path, method: :delete, class:"nav-color ml-4" %></li>
            <% end %>
          </ul>
        </nav>
        <div class="l-header_header-box">
          <ul class="l-header_header-box">
            <li class="registration">
              <%= link_to "REGISTRATION", new_user_registration_path, {class: "header-box_color"} %>
              <i class="fa fa-user-plus fa-lg header-box_icon"></i>
            </li>
            <li class="login">
              <%= link_to "LOGIN", new_user_session_path, {class: "header-box_color"} %>
              <i class="fa fa-lock fa-lg header-box_icon"></i>
            </li>
            <% if user_signed_in? %>  
              <li class="mypage">
                <%= link_to "MYPAGE", user_user_path(current_user), {class: "header-box_color"} %>
                <i class="fa fa-user fa-lg header-box_icon"></i>
              </li>
            <% end %>
          </ul>
        </div>
      </header>
      <main>
        <%= yield %>
      </main>
  </body>
</html>